name: ci

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  ci:
    name: ci
    # https://github.com/actions/runner-images/blob/main/images/macos/macos-15-Readme.md
    runs-on: macos-15
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@v14
        with:
          extra-conf: |
            sandbox = true
            sandbox-fallback = false

      - name: Nix version
        run: nix --version

      - name: Show Nix config
        run: nix config show

      - uses: DeterminateSystems/magic-nix-cache-action@v8

      # See ${workspace}/nix/overlays/xcode.nix
      - name: Xcode path
        id: xcode_path
        run: |
          XCODE_PATH=$(realpath /Applications/Xcode_16.1.0.app)
          ${XCODE_PATH}/Contents/Developer/usr/bin/xcodebuild -version

          echo "xcode_path=${XCODE_PATH}" >> $GITHUB_OUTPUT
          echo ${XCODE_PATH}

      - name: Build version
        id: version
        run: |
          case "${GITHUB_REF}" in
          refs/tags/*)
            VERSION=${GITHUB_REF#refs/tags/}
            ;;
          *)
            VERSION=develop
            ;;
          esac

          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo ${VERSION}

      # See ${workspace}/Makefile
      - name: Build
        env:
          VERSION: ${{ steps.version.outputs.version }}
          XCODE_PATH: ${{ steps.xcode_path.outputs.xcode_path }}
        run: |
          echo \"$VERSION\" > nix/utils/default/version.nix
          nix develop -c make XCODE_PATH=${XCODE_PATH}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          path: |
            result/*.tar.gz

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          fail_on_unmatched_files: true
          files: |
            result/*.tar.gz
